---
- hosts: all
  user: vagrant
  sudo: yes
  gather_facts: no
  
  tasks:
   - name: Install Rabbitmq
     apt: pkg=rabbitmq-server state=latest
   
   - name: stop rabbitmq
     service: name=rabbitmq-server state=stopped

   - name: enable rabbitmq plugins
     rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled

   - name: start rabbitmq after random sleep to stagger start
     shell: sleep {{random}}; service rabbitmq-server start
